language: cpp
sudo: true

cache: ccahe

addons: {apt: {packages: [yasm]}}

matrix:
  fast_finish: true
  include:
    # the actual compilin'
    - stage: ArchLinux
      os: linux
      env: JOB=archlinux
      services:
        - docker
    - stage: Win-Mingw-x64
      os: linux
      env:
        - JOB=mingw
        - WINARCH=x64
      services:
        - docker
    - stage: Win-Mingw-x64-qtstatic
      os: linux
      env:
        - JOB=mingw
        - WINARCH=x64
        - WITH_QT_STATIC=on
      services:
        - docker
    - stage: Win-Mingw-x32
      os: linux
      env:
        - JOB=mingw
        - WINARCH=x32
      services:
        - docker
    - stage: Win-Mingw-x32-qtstatic
      os: linux
      env:
        - JOB=mingw
        - WINARCH=x32
        - WITH_QT_STATIC=on
      services:
        - docker
    - stage: Ubuntu18-gcc
      os: linux
      env: JOB=ubuntu18
      services:
        - docker
    - stage: Ubuntu16-gcc
      os: linux
      env: JOB=ubuntu16
      services:
        - docker
    - stage: Ubuntu14-clang
      os: linux
      env: JOB=ubuntu14
    - stage: Ubuntu14-clang-qtstatic
      os: linux
      env:
        - JOB=ubuntu14
        - WITH_QT_STATIC=on
    - stage: MacOS-Xcode10.1
      os: osx
      osx_image: xcode10.1
      env: JOB=osx
    - stage: MacOS-Xcode9.4
      os: osx
      osx_image: xcode9.4
      env: JOB=osx
    - stage: MacOS-Xcode9.3
      os: osx
      osx_image: xcode9.3
      env: JOB=osx
    - stage: MacOS-Xcode8.3
      os: osx
      osx_image: xcode8.3
      env: JOB=osx
    # for ruby lower version and brew problem, not support
    # - stage: MacOS-Xcode7.3
    #   os: osx
    #   osx_image: xcode7.3
    #   env: JOB=osx
    - stage: Android-Arm7-lastest
      os: linux
      language: android
      env:
        - JOB=android
        - USEARCH=arm
        - USENDKVER=bundle
      android:
        components:
          - build-tools-26.0.2
          - android-26
          - sys-img-armeabi-v7a-android-tv-l
          - add-on
          - extra
        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
    - stage: Android-Arm7-r18b
      os: linux
      language: android
      env:
        - JOB=android
        - USEARCH=arm
        - USENDKVER=r18b
      android:
        components:
          - build-tools-26.0.2
          - android-26
          - sys-img-armeabi-v7a-android-tv-l
          - add-on
          - extra
        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
    - stage: Android-Arm7-r17c
      os: linux
      language: android
      env:
        - JOB=android
        - USEARCH=arm
        - USENDKVER=r17c
      android:
        components:
          - build-tools-26.0.2
          - android-26
          - sys-img-armeabi-v7a-android-tv-l
          - add-on
          - extra
        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
    - stage: Android-Arm7-r16b
      os: linux
      language: android
      env:
        - JOB=android
        - USEARCH=arm
        - USENDKVER=r16b
      android:
        components:
          - build-tools-26.0.2
          - android-26
          - sys-img-armeabi-v7a-android-tv-l
          - add-on
          - extra
        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
    - stage: Android-X86
      os: linux
      language: android
      env:
        - JOB=android
        - USEARCH=x86
        - USENDKVER=bundle
      android:
        components:
          - build-tools-26.0.2
          - android-26
          - sys-img-armeabi-v7a-android-tv-l
          - add-on
          - extra
        licenses:
          - 'android-sdk-preview-license-52d11cd2'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'

script: "./.travis/build-main.sh"

before_install:

before_script:




